# Rust formatting configuration
# See: https://rust-lang.github.io/rustfmt/

edition = "2024"

fn_params_layout = "Tall"
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 100
merge_derives = true
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = false
use_small_heuristics = "Default"
use_try_shorthand = true
